### ISSUE TITLE
ぱっとやった実験結果

### ISSUE THREAD

**Issue by awakia** [awakia/double-db#1]
## 実験前提

User has_one Profile
Profile has_many WorkingHistory

User => FirstDB
Profile, WorkingHistory => SecondDB

## 実験結果

![image](https://user-images.githubusercontent.com/272083/31711616-b3eda272-b433-11e7-8682-fe24ae930e0a.png)

思ったよりうまくいく。
Associationを利用したcreateとか周りはうまく動くし、
eager_loadするとダメだけど、preloadは問題なく動く。

まぁ単純にJoinにならないパターンはOKなんだろう。

**Comment by awakia** [comment]
一方FactoryGirlは空気読まずにあまりうまくいかない

**Comment by izumin5210** [comment]
↓rspec実行結果

```
:) % rid rspec
awakiadoubledb_volume_1 is up-to-date
awakiadoubledb_app_1 is up-to-date
*F*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Profile add some examples to (or delete) /app/spec/models/profile_spec.rb
     # Not yet implemented
     # ./spec/models/profile_spec.rb:4

  2) WorkingHistory add some examples to (or delete) /app/spec/models/working_history_spec.rb
     # Not yet implemented
     # ./spec/models/working_history_spec.rb:4


Failures:

  1) User associations works
     Failure/Error: u3 = User.eager_load(profile: :working_histories).to_a.last

     ActiveRecord::StatementInvalid:
       PG::UndefinedTable: ERROR:  relation "profiles" does not exist
       LINE 1: ...updated_at" AS t2_r4 FROM "users" LEFT OUTER JOIN "profiles"...
                                                                    ^
       : SELECT "users"."id" AS t0_r0, "users"."name" AS t0_r1, "users"."created_at" AS t0_r2, "users"."updated_at" AS t0_r3, "profiles"."id" AS t1_r0, "profiles"."user_id" AS t1_r1, "profiles"."location" AS t1_r2, "profiles"."created_at" AS t1_r3, "profiles"."updated_at" AS t1_r4, "working_histories"."id" AS t2_r0, "working_histories"."profile_id" AS t2_r1, "working_histories"."company" AS t2_r2, "working_histories"."created_at" AS t2_r3, "working_histories"."updated_at" AS t2_r4 FROM "users" LEFT OUTER JOIN "profiles" ON "profiles"."user_id" = "users"."id" LEFT OUTER JOIN "working_histories" ON "working_histories"."profile_id" = "profiles"."id"
     # ./spec/models/user_spec.rb:21:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::UndefinedTable:
     #   ERROR:  relation "profiles" does not exist
     #   LINE 1: ...updated_at" AS t2_r4 FROM "users" LEFT OUTER JOIN "profiles"...
     #                                                                ^
     #   ./spec/models/user_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 0.24999 seconds (files took 4.23 seconds to load)
3 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/models/user_spec.rb:6 # User associations works
```

怒られている行

https://github.com/awakia/double-db/blob/ffe1bbb70b4cc1f06c876dfe141b231e986d428f/spec/models/user_spec.rb#L21

`eager_load`なのでleft outer joinしようとして怒られている
